name : PMD

on :
  push:
  pull_request:

jobs:
  PMD_analysis:
    name: Run PMD Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/'
          analyzeModifiedFilesOnly: 'false'
          format: 'text'
          failOnViolation: true
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'